name: Deploy-Action
on: 
  push: 
    branch: 
      -main
jobs: 
  build-and-deploy: 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['15', '16']
    steps: 
      - name: Use Checkout
        uses: actions/checkout@v2

      - name: Use Pnpm
        uses: pnpm/action-setup@v2.0.1
        with: 
          version: 6.20.3
      
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'

      - name: Install packages
        run: npm ci
      
      - name: Build project
        run: npm run build
      
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: prod
          folder: dist
